### ISSUE TITLE
Cannot find class [org.openqa.selenium.remote.DesiredCapabilities] when running with Chrome

### ISSUE THREAD

**Issue by nottyo** [jspringbot/jspringbot-selenium#1]
Hi,
   I've setup my jspringbot-selenium project to be running with Chrome. I found an error message while the test is initializing. 
`Cannot find class [org.openqa.selenium.remote.DesiredCapabilities] for bean with name 'desiredCapabilities' defined in class path resource [spring/spring-selenium-chrome.xml]`

`Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.DesiredCapabilities`

You can see my sample project on [https://github.com/nottyo/jspringbot-webtesting](https://github.com/nottyo/jspringbot-webtesting)

My project is using jspringbot-selenium 1.5

**Comment by badong2210** [comment]
Okay. I will check it

**Comment by badong2210** [comment]
Hello, 

Your project is running on my end using "mvn clean integration-test" command.

Can you check if chromedriver was downloaded under jspringbot folder in home directory ?

ex ~/jspringbot/
- chromedriver
- chromedriver_mac64.zip

Can you also make sure chromedriver is not being used before you run the test ( cmd + shift + esc ) ?

**Comment by nottyo** [comment]
Yes, there is chromedriver downloaded in ~/jspringbot
After I run my project with command "mvn clean integration-test", it throws the same error message
`Initializing test library 'JSpringBotGlobal' with no arguments failed: CannotLoadBeanClassException: Cannot find class [org.openqa.selenium.remote.DesiredCapabilities] for bean with name 'desiredCapabilities' defined in class path resource [spring/spring-selenium-chrome.xml]; nested exception is java.lang.ClassNotFoundException: org.openqa.selenium.remote.DesiredCapabilities`

I'm sure that there is no any process are using chromedriver before I run the test.

`~/jspringbot/chromedriver --version
ChromeDriver 2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6)`

I can run my project if I changed the jspringbot-base version to 1.4

**Comment by badong2210** [comment]
Upgrade to jdk1.8 and run using jspringbot-base 1.5.

**Comment by nottyo** [comment]
I'm running with JDK1.8 Update 91 with jspring-base 1.5 and get the same error message.

**Comment by shiela-mnltech** [comment]
Your repo maybe corrupted and was not able to properly find the selenium dependency. My suggestion is to remove the .m2 directory so the dependency will be re-downloaded.

**Comment by badong2210** [comment]
Your repo maybe corrupted and was not able to properly find the selenium dependency. My suggestion is to remove the .m2 directory so the dependency will be re-downloaded.

**Comment by nottyo** [comment]
Oh, I'm so sorry. My Maven dependencies are corrupted like you said. I clean and re-build the project, then it works fine! 

Thank you for your support.
